"""Weekly compliance report rendering.

Two sources, one renderer:
- the cloud app summarizes verdicts POSTed to /diagnose (GET /report/weekly)
- the CLI summarizes an edge audit db (`permafrost report --week N --db ...`)

Production note: the weekly sweep is priced for the **Batch API** (-50%); this
build renders the same report synchronously (Batch submission pending — see
README Status).
"""

from __future__ import annotations

from collections import Counter
from typing import Any

from ..timeutil import iso_week_of
from ..verdict import is_critical_dict

__all__ = ["weekly_report_markdown"]


def weekly_report_markdown(
    week: int,
    verdicts: list[dict[str, Any]],
    *,
    fridge_id: str = "clinic-fridge-01",
    readings: int | None = None,
    in_band_pct: float | None = None,
    chain_summary: str | None = None,
    roots_signed: int | None = None,
) -> str:
    """Render the VFC-style weekly summary as markdown."""
    in_week = [v for v in verdicts if "ts" not in v or iso_week_of(float(v["ts"])) == week]
    causes = Counter(str(v.get("cause", "unknown")) for v in in_week)
    benign = sum(1 for v in in_week if v.get("benign"))
    critical = sum(1 for v in in_week if is_critical_dict(v))
    task_ids = [str(v.get("task_id", "")) for v in in_week if v.get("task_id")]

    lines = [
        f"# Permafrost weekly compliance report — ISO week {week}",
        "",
        f"Fridge: `{fridge_id}`",
        "",
        "## Summary",
        "",
        f"- Excursion verdicts: **{len(in_week)}** ({benign} benign, {critical} critical)",
    ]
    if readings is not None:
        lines.append(f"- Readings logged: **{readings}**")
    if in_band_pct is not None:
        lines.append(f"- Time in 2-8 C band: **{in_band_pct:.1f}%**")
    if roots_signed is not None:
        lines.append(f"- Signed daily Merkle roots: **{roots_signed}**")
    if chain_summary is not None:
        lines.append(f"- Hash-chain audit: **{chain_summary}**")
    lines += ["", "## Verdicts by cause", ""]
    if causes:
        lines.append("| cause | count |")
        lines.append("|---|---|")
        for cause, n in sorted(causes.items()):
            lines.append(f"| {cause} | {n} |")
    else:
        lines.append("_No excursions this week — frozen safe._")

    crit_rows = [v for v in in_week if is_critical_dict(v)]
    if crit_rows:
        lines += ["", "## Critical events (each cites guidance — invariant I4)", ""]
        for v in crit_rows:
            lines.append(f"- **{v.get('cause')}** (confidence {v.get('confidence')}): {v.get('guidance_citation', '')[:140]}")
    if task_ids:
        lines += ["", "## Qwen task ids", ""]
        for t in task_ids[:20]:
            lines.append(f"- `{t}`")
    lines += [
        "",
        "---",
        "_Generated by Permafrost. Weekly sweeps are priced for the Qwen Batch API (-50%); "
        "this report was rendered synchronously (Batch submission pending)._",
    ]
    return "\n".join(lines)
